/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "common": {
        "100500": string;
    };
    "user": {
        "101000": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
