/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "chacter": {
        "NAME": string;
    };
    "common": {
        "100200": string;
        "100201": string;
        "100500": string;
        "HAS_EXITTED_MERGE": string;
        "NOT_EXIST_MERGE": string;
        "NOT_CLOSE_MERGE": string;
        "NOT_DELETE_MERGE": string;
        "NOT_ENABLE_MERGE": string;
        "NOT_DISABLE_MERGE": string;
        "NOTICE_CREATE": string;
        "NOTICE_UPDATE": string;
        "NOTICE_DELETE": string;
    };
    "http": {
        "HTTP_CREATE_SUCCESS": string;
        "HTTP_UPDATE_SUCCESS": string;
        "HTTP_DELETE_SUCCESS": string;
        "HTTP_SERVICE_FAIL": string;
        "HTTP_LOGIN_SUCCESS": string;
        "HTTP_REGISTER_SUCCESS": string;
    };
    "user": {
        "101000": string;
        "101001": string;
        "101002": string;
        "101003": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
