/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "chacter": {
        "name": string;
        "command": {
            "value": string;
            "required": string;
        };
        "cn": {
            "value": string;
            "required": string;
        };
        "en": {
            "value": string;
            "required": string;
        };
    };
    "common": {
        "HAS_EXITTED_MERGE": string;
        "NOT_EXIST_MERGE": string;
        "NOT_CLOSE_MERGE": string;
        "NOT_DELETE_MERGE": string;
        "NOT_ENABLE_MERGE": string;
        "NOT_DISABLE_MERGE": string;
        "comment": {
            "value": string;
        };
    };
    "http": {
        "CREATE_SUCCESS": string;
        "UPDATE_SUCCESS": string;
        "DELETE_SUCCESS": string;
        "SERVICE_ERROR": string;
    };
    "router": {
        "name": string;
    };
    "rule": {
        "name": string;
    };
    "user": {
        "name": string;
        "notice": {
            "LOGIN_NOT": string;
            "LOGIN_SUCCESS": string;
            "REGISTER_SUCCESS": string;
        };
        "nickname": {
            "value": string;
        };
        "email": {
            "value": string;
        };
        "avatar": {
            "value": string;
        };
        "openid": {
            "value": string;
        };
        "mobile": {
            "value": string;
            "required": string;
            "register": string;
        };
        "password": {
            "value": string;
            "required": string;
            "error": string;
        };
        "code": {
            "value": string;
            "required": string;
            "error": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
